add volto translation jobs for master and 16.x.x
plone/jenkins.plone.org pull request #324
Opened 2022-12-02 11:12 UTC by erral

Now that we have Volto 16.x.x LTS in its own branch, it is worth to have the translation status for it and `master` also.

Can you review if the syntax is OK and if so deploy it?

2022-12-02 13:54 UTC, gforcada requested changes
Great job, one minimal fix and we can deploy 🚀

2022-12-02 13:54 UTC, gforcada commented on jobs/jobs.yml
> +
You don't need to create 2 `project:` keys, something like this is enough:

```yml
project:
    name: Translations Volto
    branch:
        - '16.x.x'
        - 'master'
    jobs:
        - 'volto-translations-{branch}'
```
🍀

2022-12-02 13:57 UTC, erral commented
done!

2022-12-03 01:10 UTC, gforcada approved these changes

2022-12-03 01:10 UTC, merged

2022-12-03 01:11 UTC, gforcada commented
@erral changes are tested, jobs have been pushed, and are [already green](https://jenkins.plone.org/view/Translations/) 🍀 

I disabled the _old job_ ([this one](https://jenkins.plone.org/view/Translations/job/Volto%20translations/)), let me know if it can be 💥

2022-12-03 05:36 UTC, erral commented
yes that's right, you can disable the old one. thanks !