handle volto translations jobs
plone/jenkins.plone.org pull request #366
Opened 2024-08-21 09:45 UTC by erral

We need specific jobs for each branch, because in 16.x.x and 17.x.x Volto lives in the root of the repo and in main it lives in `packages/volto`

Addresses https://github.com/plone/jenkins.plone.org/commit/3a5eb9e3b2e82843b38b49d4ea780f0dafb90725#commitcomment-145590810

2024-08-21 09:47 UTC, erral commented
I don't know whether the `{branch}` trick will work in the command...

2024-08-24 06:46 UTC, gforcada requested changes

2024-08-24 06:46 UTC, gforcada commented on jobs/jobs.yml
> +          command: !include-raw: scripts/volto-i18n-{branch}.sh
I don't think this will work, we usually use that branch within the script and use `if/else` there 😄 

I can amend it for you 👍🏾

2024-08-24 07:04 UTC, gforcada approved these changes

2024-08-24 07:04 UTC, gforcada commented
The jobs are up and running 🎉

2024-08-24 07:04 UTC, merged